version: '3.8'
services:
  traefik:
    image: "traefik:v3.5"
    container_name: "traefik"
    command: 
      - "--providers.docker=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=your-email-here"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
    environment:
      - CLOUDFLARE_EMAIL=your-cloudflare-email-here
      - CLOUDFLARE_DNS_API_TOKEN=your-dns-api-token-here
      - CLOUDFLARE_ZONE_API_TOKEN=your-zone-api-token-here
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  recbot:
    image: ghostreaper69/recbot:v1.5.23
    container_name: "recbot"
    labels:
      - traefik.enable=true
      # Removed custom header rewrites; Traefik already sets X-Forwarded-For and preserves CF-Connecting-IP from Cloudflare.
      - traefik.http.routers.recbot.rule=Host(`your-domain-here`)
      - traefik.http.routers.recbot.entrypoints=websecure
      - traefik.http.routers.recbot.tls.certresolver=letsencrypt
      - traefik.http.services.recbot.loadbalancer.server.port=4000
    volumes:
      - ./data/sqlite:/root/db
    ports:
      - "4000:4000"
      #- "2222:2222"
    environment:
      # --- Core App Configuration ---
      - NODE_ENV=production
      - PORT=4000
      - STORAGE_TYPE=aws
      - WAV_DIR=/data/wav
      - DB_PATH=/root/db/recbot.db

      # --- AWS S3 (required) ---
      - AWS_ACCESS_KEY_ID=your-aws-access-key-id-here
      - AWS_SECRET_ACCESS_KEY=your-aws-secret-access-key-here
      - AWS_REGION=your-aws-region-here
      - AWS_BUCKET=your-aws-bucket-name-here

      # --- Clerk Authentication ---
      - CLERK_PUBLISHABLE_KEY=pk_test_your_clerk_publishable_key_here
      - CLERK_SECRET_KEY=sk_test_your_clerk_secret_key_here
      - ALLOWED_EMAIL_DOMAIN=mtgpros.com
      - REACT_APP_CLERK_PUBLISHABLE_KEY=pk_test_your_clerk_publishable_key_here

      # --- Session & Security Controls ---
      - MAX_SESSION_HOURS=4
      - MAX_INACTIVITY_MINUTES=30
      - MAX_ACTIVE_WINDOW_MIN=30

      # --- Frontend Runtime Config (if SPA served separately) ---
      - REACT_APP_API_URL=https://your-domain-here/api

      # --- Optional / Feature Flags ---
      - ENABLE_SFTP=false
      #- SFTP_USER=root
      #- SFTP_PASS=your_sftp_password_here
      #- EXTRA_LOGGING=true
      #- LOG_LEVEL=info

      # --- Future / Reserved Variables (uncomment as needed) ---
      #- CDN_BASE_URL=https://cdn.your-domain-here
      #- FORCE_HTTPS=true
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN  # Required for FUSE
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined  # Required for FUSE on some systems
    # Uncomment to persist logs or mount local folders if needed
    # volumes:
    #   - ./local_wav:/data/wav
    #   - ./logs:/var/log
